### PR TITLE
Improve error reporting and fix wgs accession bugs

### PR DESCRIPTION
**Pull request by josieburgin**

### CODE REVIEW

**Review by suranjayathilaka — CHANGES_REQUESTED** [review]
can merge the 2 patterns into one
^[A-Z]{4}[0-9]{2}$' + ^[A-Z]{6}[0-9]{2}$' ->
^[A-Z]{4,6}[0-9]{2}$
technically this allow 4 to 6 chars as prefix, but safe enough.
or
^([A-Z]{4}|[A-Z]{6})[0-9]{2}$  to be strict

**Review by suranjayathilaka — CHANGES_REQUESTED** [review]
why not combine wgs_master_pattern_1 & 2? e.g. {8,9} specifies min and max count allowed.

**Comment by josieburgin** [comment]
I have in my records that unversioned wgs master accessions with a prefix of 4 characters should only have 8 0s to be valid but accessions with a prefix of 6 should have 9 0s which is why I didn't merge these (to keep the validation precise). If this is not the case then I can change it.

**Comment by suranjayathilaka** [comment]
Understood. However this is not strictly defined afaik. For ref, masters with 4 char sets it's 2 version digits + 6-8 zeroes. with 6 char sets it's 2 version digits + 7-9  zeroes. In the Browser we support just set name + version digits without any zeroes as well.

So it's a bit of a compromise. Might as well be inclusive here and handle extra zeroes in backend if it comes to that.

**Review by suranjayathilaka — CHANGES_REQUESTED** [review]
this needs to allow the version digits that be anything from 01-99. only count 0s after the 1st 2 digits.
unversion_wgs_master_pattern = re.compile('^([A-Z]{4}|[A-Z]{6})[0]{8,11}$')

**Review by suranjayathilaka — APPROVED** [review]
thanks

**Pull request merged**
